twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        project_title: Patryk Sitek
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
when@test:
    twig:
        strict_variables: true
        form_themes:
        - 'form/custom_types.html.twig'
        - '...'
