<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVf5BV2L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVf5BV2L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVf5BV2L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVf5BV2L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVf5BV2L\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vf5BV2L',
    'container.build_id' => '61f2a6f7',
    'container.build_time' => 1653848926,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVf5BV2L');
