<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH4dKZpJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH4dKZpJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH4dKZpJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH4dKZpJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH4dKZpJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'H4dKZpJ',
    'container.build_id' => 'f9b61d22',
    'container.build_time' => 1655464334,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH4dKZpJ');
