<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5E1duBw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5E1duBw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5E1duBw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5E1duBw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5E1duBw\App_KernelDevDebugContainer([
    'container.build_hash' => '5E1duBw',
    'container.build_id' => '49cdb442',
    'container.build_time' => 1655495567,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5E1duBw');
